### ISSUE TITLE
Cosmic Ray Code not Compiling

### ISSUE THREAD

**Issue by Neoshika** [TESScience/SPyFFI#11]
In the course of installing SPyFFI on another user's computer, I could not get Al Levine's cosmic ray code to compile. I don't have the exact error message, but the gist of it was a missing file named `setup.py` in the cosmical_realistic directory.

Copying the `setup.py` from the `cosmical_realistic` directory of Zach's legacy branch into the new one fixed the problem. That file's entire contents are:

```
from setuptools import setup, Extension
import numpy.distutils.misc_util

setup(install_requires=['numpy'],
      ext_modules=[Extension("_cosmical", ["_cosmical.c", "cosmical.c", "twister.c", "seed_tw_ran.c"],
                             include_dirs=numpy.distutils.misc_util.get_numpy_include_dirs())], )
```

**Comment by xcthulhu** [comment]
I renamed that file to `compile_module`:
https://github.com/TESScience/SPyFFI/blob/04298fdc92f5ec0ed050cd270dd3179761d2ffda/cosmical_realistic/compile_module

This is because `cosmical_realistic/setup.py` was getting included in the `pip` installation of SPyFFI, which isn't the right behavior.

You can just go into the `cosmical_realistic` directory and type `make` now and it should be fine.

Can you confirm this is okay?

**Comment by Neoshika** [comment]
Make in cosmical_realistic throws 14 warning messages, but compiles properly for me.
